= StudyGuide - Licensing NOTICE
:numbered:

Copyright (C) 2015, Ondrej Skopek.

See the LICENSE file for licensing details.

All Authors and Contributors are named in the link:AUTHORS.html[AUTHORS] file.

== Used libraries

=== Apache Commons Lang

https://commons.apache.org/proper/commons-lang/

License: APL v2.0

Apache Commons Lang
Copyright 2001-2016 The Apache Software Foundation

This product includes software developed at
The Apache Software Foundation (http://www.apache.org/).

This product includes software from the Spring Framework,
under the Apache License 2.0 (see: StringUtils.containsWhitespace())

=== JUnit

http://junit.org/

License: EPL v1.0

=== Logback

http://logback.qos.ch/

License: dual EPL v1.0 & LGPL 2.1

Logback: the reliable, generic, fast and flexible logging framework.
Copyright (C) 1999-2015, QOS.ch. All rights reserved.

This program and the accompanying materials are dual-licensed under
either the terms of the Eclipse Public License v1.0 as published by
the Eclipse Foundation

  or (per the licensee's choosing)

under the terms of the GNU Lesser General Public License version 2.1
as published by the Free Software Foundation.

=== Jackson

http://wiki.fasterxml.com/JacksonHome

License: APL v2.0

=== Simmetrics

https://github.com/Simmetrics/simmetrics

License: APL v2.0

=== JSoup

http://jsoup.org/

License: MIT

jsoup: Java HTML parser that makes sense of real-world HTML soup.

=== Guava

https://github.com/google/guava

License: APL v2.0

Guava: Google Core Libraries for Java 6+

=== Weld

http://weld.cdi-spec.org/

License: APL v2.0

Weld: Contexts and Dependency Injection for the Java Platform.

=== Mockito

http://mockito.org/

License: MIT

Mockito: Tasty mocking framework for unit tests in Java
