= StudyGuide -- zápočtový program, Java, ZS 2015
Ondrej Škopek <oskopek@matfyz.cz>

== Stručne

Program StudyGuide je ideálny sprievodca štúdiom každého matfyzáka (i nematfyzáka).

Umožňuje študentom "európskeho" typu štúdia na univerzite monitorovať priebeh svojho štúdia,
jednoducho prezerať splnenosť jednotlivých podmienok svojho odboru -- a tým predísť
nepríjemným prekvapeniam na študíjnom oddelení!

== Podrobne

Typický workflow študenta v StudyGuide:

1. Študent si do StudyGuide načíta zoznam predmetov, ktoré si následne rozvrhne do semestrov
2. Môže predmety prehadzovat, postupne označovať ako splnené/nesplnené, ...
3. StudyGuide vždy udržuje aktuálny a plánovaný stav splnenosti jednotlivých podmienok
4. Študent jasne a prehľadne vidí, čo mu v pláne/realite chýba do splnenia študíjnych povinností -- a môže podľa toho konať
5. Študent taktiež môže vytvárat rôzne scenária -- skúsiť si, čo sa stane, ak tú či onú povinnosť nesplní, ak si zapíše iné predmety, ...

== Funkcionalita

Program bude obsahovať:

* Aktuálne datové súbory pre všetky typy bakalárskeho (prípadne i magisterského) štúdia na MFF
* Podporu rôznych univerzitných, fakultných a odborových kriterií na úspešnosť štúdia
* Rýchle prepočítavanie kontrol podľa aktuálne zvoleného študijneho plánu (zapísaných predmetov)
* Možnosť ukladať/načítavať vytvorené študíjne plány, prípadne fiktívne scenáre
* Jednoduché JavaFX grafické prostredie na editáciu aktuálneho študíjneho plánu a zobrazenie výsledkov kontrol

