= StudyGuide -- zápočtový program, Java, ZS 2015
Ondrej Škopek <oskopek@matfyz.cz>


TODO: Revise, politically correct tone, zhodnotit narocnost

== Stručne

Program StudyGuide je ideálny sprievodca štúdiom každého matfyzáka (i nematfyzáka...).
Umožňuje študentom "európskeho" typu štúdia na univerzite monitorovať priebeh svojho štúdia,
jednoducho prezerať splnenosť jednotlivých podmienok svojho odboru -- a tým predísť
nepríjemným prekvapeniam na študíjnom oddelení!

== Podrobne

Typický workflow študenta v StudyGuide:
1. Študent si do program načíta svoj odbor a príslušné podmienky potrebné na jeho splnenie (povinné predmety, skupiny povinne voliteľných predmetov, ...)
2. StudyGuide vie z rôznych* datových zdrojov načítať zoznam predmetov, ktoré si študent rozvrhne do semestrov
3. Študent môže predmety prehadzovat, označovať ako splnené/nesplnené, ...
4. StudyGuide vždy udržuje aktuálny stav a plánovaný stav splnenosti jednotlivých podmienok, ktoré určuje vybratý odbor
5. Študent jasne a prehľadne vidí, čo mu v pláne/realite chýba do splnenia študíjnych povinností
6. Student si moze vytvarat rozne scenaria -- skusit si, co sa stane, ak tu ci onu povinnost nesplnim

Program bude určite obsahovať:

* Aktuálne datové súbory pre všetky typy Bakalarskeho/Magisterskeho studia na MFF
* Podporu roznych univerzitnych, fakultnych a odborovych kriterii na uspesnost studia
* Rychle prepocitavanie statistik na zaklade
* Moznost ukladat/nacitavat vytoverene plany/scenare

== Bonus

* Localization (EN, DE, SK, CZ)
* Dynamicke generovanie vstupnych nastaveni/suborov z textovych zdrojov (pdf, html, ...)
* Dynamicke generovanie vstupnych nastaveni/suborov z databazovych zdrojov (SIS, IS, ...)
* Varovanie na prekrocenie doby studia/poplatky
* Vyhodnocovanie "narocnosti" daneho zapisaneho planu na semester podla europskych noriem (funkcia hodinovej dotacie, kreditov, ...)

= Zápočtový program, Pokročilé programování na platformě Java
Ondrej Škopek <oskopek@matfyz.cz>

StudyGuide 2

== Stručne

Program StudyGuide je ideálny sprievodca štúdiom každého matfyzáka (i nematfyzáka...).
Umožňuje študentom "európskeho" typu štúdia na univerzite monitorovať priebeh svojho štúdia,
jednoducho prezerať splnenosť jednotlivých podmienok svojho odboru -- a tým predísť
nepríjemným prekvapeniam na študíjnom oddelení!

== Podrobne

Program bude rozšírením zápočtového programu z predchádzajúceho semestru.
Pridané budú následovné časti:

* Program vie vygenerovat zo SISu a aktualnych studijnych vysledkov subor pre vstup
* Dokoncenie lokalizacie (EN, DE, SK, CZ)
* SaaS --> Web UI w/Drag'n'Drop, etc.

== Bonus

* ???Integracia priamo do SIS???
