= StudyGuide Manual (EN)
:sectnums:

Welcome to StudyGuide's manual!
StudyGuide is a planning and verifying tool for all the requirements of your studies (for European-style university school systems).

== Typical workflow

Typical workflow of a StudyGuide user/student:

1. Student loads a study plan with courses, that he then enrolls in and distributes among semesters
2. Môže predmety prehadzovat, postupne označovať ako splnené/nesplnené, ...
3. StudyGuide vždy udržuje aktuálny a plánovaný stav splnenosti jednotlivých podmienok
4. Študent jasne a prehľadne vidí, čo mu v pláne/realite chýba do splnenia študíjnych povinností -- a môže podľa toho konať
5. Študent taktiež môže vytvárat rôzne scenária -- skúsiť si, čo sa stane, ak tú či onú povinnosť nesplní, ak si zapíše iné predmety, ...

== Load and save a study plan

=== Demo plans

MFF plans

== Edit your study plan

=== Adding/removing semesters

Click on the "%semesterPane.addSemester" button.

=== Adding new courses

=== Add a course from SIS (TODO version 1.0.0)

=== Enrolling in a course

And moving the enrollment

== Verifying constraints

=== Fulfilling course enrollments

=== Course enrollment constraints

=== Global / course-group constraints

=== Semester statistics (TODO version 1.0.0)

Fulfilled/Total, ECTS hours estimation

== Changing StudyGuide's language (TODO version 1.0.0)

Localization

== Scrape a study plan from a URL (TODO version 1.0.0)


