== Using StudyGuide
:source-highlighter: coderay

//TODO finish this

=== TODO Running the StudyGuide command line demo

If you want to run a little demo of StudyGuide, follow these quick instructions.

Firstly, create these directories:

* *Default input directory*: `$HOME/dev/java/StudyGuide_data/in`
* *Default output directory*: `$HOME/dev/java/StudyGuide_data/out`

Now you need to populate the *input directory*.
The easiest way to do that is by copying the `img` directory from `StudyGuide-core/src/test/resources` to the input directory.

You should now have a directory structure that looks something like this:

[source,bash]
----
[oskopek@sauron carcv_data]$ tree
.
├── in
│   └── img
│       ├── skoda_oct.jpg
│       ├── sources.txt                                                                                                                                                                 
│       └── test_041.jpg                                                                                                                                                                
└── out                                                                                                                                                                                 
                                                                                                                                                                                        
3 directories, 3 files
----

After running `mvn exec:java` in the `carcv/carcv-core/` directory, the input/output directories should look like this:

[source,bash]
----
[oskopek@sauron carcv_data]$ tree                                                                                                                                                       
.                                                                                                                                                                                       
├── in                                                                                                                                                                                  
│   └── img                                                                                                                                                                             
│       ├── info.properties                                                                                                                                                             
│       ├── skoda_oct.jpg                                                                                                                                                               
│       ├── sources.txt                                                                                                                                                                 
│       └── test_041.jpg
└── out
    ├── skoda_oct.jpg.properties
    └── test_041.jpg.properties

3 directories, 6 files
----

View the `.properties` files in `out` for results.

=== Using the default implementation of CarRecognizer

To use +carcv-core+ (number plate detection and speed detection) in your application,
simply instantiate a +FileCarRecognizer+ (the default implementation of +CarRecognizer+).

For example, in +carcv-webapp+ we use this method in +RecognizerBean+ like this:

[source,java]
----
@Stateless
public class RecognizerBean {
    private FileCarRecognizer recognizer = new FileCarRecognizer(Path inputDirectory, Path outputDirectory);

    public void recognize() throws IOException {
        recognizer.recognize();
    }
}
----

This assumes you use a data input and output directory in a filesystem +java.nio+ can access.

=== Using your own implementation of CarRecognizer

If you wish to implement it yourself, simply extend the +CarRecognizer+ abstract class.
Notes on implementation details are in the javadoc for +CarRecognizer+. 
To see the default implementation, see the +org.carcv.impl+ packages.